### ISSUE TITLE
[code-review] Не использованы Alias и Type-Hint для внедрения кеша в контроллер

### ISSUE THREAD

**Issue by sheerockoff** [SergeyKozadaev/symfonyLibrary#2]
Объявлен сервис кеша с поддержкой тегов:
https://github.com/SergeyKozadaev/symfonyLibrary/blob/f609c2c47628358ad8fe77b73ae81c536b2dab13/config/services.yaml#L27-L30

Внедрение кеша в контроллер реализовано через биндинг аргументов:
https://github.com/SergeyKozadaev/symfonyLibrary/blob/f609c2c47628358ad8fe77b73ae81c536b2dab13/config/services.yaml#L44-L50

В аргументе $cache контроллера не используется type-hinting:
https://github.com/SergeyKozadaev/symfonyLibrary/blob/f609c2c47628358ad8fe77b73ae81c536b2dab13/src/Controller/BookController.php#L31

Если использовать alias для сервиса кеша, то можно избавиться от "ручного" биндинга кеша в контроллер, используя type-hint. Пример:
```yaml
# config/services.yaml

myapp.cache:
        public: true
        class: Symfony\Component\Cache\Adapter\TagAwareAdapter
        arguments: ['@app.cache.file']

Symfony\Component\Cache\Adapter\TagAwareAdapter: '@myapp.cache'
```
```php
// src/Controller/BookController.php

public function list(TagAwareAdapter $cache, Request $request, BookRepository $repository, PaginatorInterface $paginator) 
```

Документация по теме: https://symfony.com/doc/current/service_container/autowiring.html#using-aliases-to-enable-autowiring
