### ISSUE TITLE
[code-review] Файл services.yaml содержит специфичные для окружения настройки

### ISSUE THREAD

**Issue by sheerockoff** [SergeyKozadaev/symfonyLibrary#5]
https://github.com/SergeyKozadaev/symfonyLibrary/blob/f609c2c47628358ad8fe77b73ae81c536b2dab13/config/services.yaml#L14

В файле `services.yaml` рекомендуется не раскрывать специфичные для окружения настройки. Цитата: `Put parameters here that don't need to change on each machine where the app is deployed`.

Определять подобные настройки рекомендуется в `.env`. Например:
```ini
# .env
API_V1_KEY="some_key"
```
```yaml
# config/services.yaml
parameters:
  api_v1_key: '%env(API_V1_KEY)%'
```

Документация: https://symfony.com/doc/current/configuration/external_parameters.html#environment-variables
